# Generated by Django 6.0.2 on 2026-02-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('UZS', 'O‘zbek so‘mi'), ('USD', 'AQSH dollari'), ('EUR', 'Yevro')], default='UZS', max_length=3),
        ),
    ]
